/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.AccountDAO;
import DTO.AccountDTO;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author NCT
 */
public class jfAccount2 extends javax.swing.JFrame {

    /**
     * Creates new form jfAccount2
     */
    protected AccountDTO Acc;
    
    
    public jfAccount2() {
        initComponents();
        pnDoiMatKhau2.setVisible(false);
        pnThemTK2.setVisible(false);

    }
    
        public jfAccount2(AccountDTO acc) {
        initComponents();
        Acc = acc;
        pnDoiMatKhau2.setVisible(false);
        pnThemTK2.setVisible(false);
        loadPanelThongTin();
    }
    
    
   void setColor(JPanel pn){
        pn.setBackground(new Color(0,204,255));
    }
    
    void resetColor(JPanel pn){
        pn.setBackground(new Color(0,153,255));
    }
    
    private void loadPanelThongTin(){
        txtTen.setText(Acc.getHoTen());
        txtDiaChi.setText(Acc.getDiaChi());
        txtSDT.setText(Acc.getSDT());
    }
    
    private void loadPanelThemTK(){
        txtTenAdd.setText("");
        txtDiachiAdd.setText("");
        txtSDTAdd.setText("");
        txtPass.setText("");
        txtUserName.setText("");
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnChucNang = new javax.swing.JPanel();
        pnThongTin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnThemTK = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnDoiMatKhau = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnBack = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnNen = new javax.swing.JPanel();
        pnThongTin2 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        btCapNhatTK = new javax.swing.JButton();
        pnDoiMatKhau2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btCapNhatMK = new javax.swing.JButton();
        txtMKCu = new javax.swing.JPasswordField();
        txtMKMoi = new javax.swing.JPasswordField();
        txtMKMoi2 = new javax.swing.JPasswordField();
        pnThemTK2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTenAdd = new javax.swing.JTextField();
        txtDiachiAdd = new javax.swing.JTextField();
        txtSDTAdd = new javax.swing.JTextField();
        btTaoTK = new javax.swing.JButton();
        txtUserName = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtPass = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cbLoaiTK = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(55, 204, 255));

        pnChucNang.setBackground(new java.awt.Color(51, 153, 255));
        pnChucNang.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnChucNangMouseMoved(evt);
            }
        });

        pnThongTin.setBackground(new java.awt.Color(0, 153, 255));
        pnThongTin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnThongTinMouseMoved(evt);
            }
        });
        pnThongTin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnThongTinMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cập nhật thông tin");

        javax.swing.GroupLayout pnThongTinLayout = new javax.swing.GroupLayout(pnThongTin);
        pnThongTin.setLayout(pnThongTinLayout);
        pnThongTinLayout.setHorizontalGroup(
            pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pnThongTinLayout.setVerticalGroup(
            pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pnThemTK.setBackground(new java.awt.Color(51, 153, 255));
        pnThemTK.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnThemTKMouseMoved(evt);
            }
        });
        pnThemTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnThemTKMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Thêm tài khoản NV");

        javax.swing.GroupLayout pnThemTKLayout = new javax.swing.GroupLayout(pnThemTK);
        pnThemTK.setLayout(pnThemTKLayout);
        pnThemTKLayout.setHorizontalGroup(
            pnThemTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThemTKLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        pnThemTKLayout.setVerticalGroup(
            pnThemTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThemTKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pnDoiMatKhau.setBackground(new java.awt.Color(51, 153, 255));
        pnDoiMatKhau.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnDoiMatKhauMouseMoved(evt);
            }
        });
        pnDoiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnDoiMatKhauMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Đổi mật khẩu");

        javax.swing.GroupLayout pnDoiMatKhauLayout = new javax.swing.GroupLayout(pnDoiMatKhau);
        pnDoiMatKhau.setLayout(pnDoiMatKhauLayout);
        pnDoiMatKhauLayout.setHorizontalGroup(
            pnDoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDoiMatKhauLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(25, 25, 25))
        );
        pnDoiMatKhauLayout.setVerticalGroup(
            pnDoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDoiMatKhauLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pnBack.setBackground(new java.awt.Color(51, 153, 255));
        pnBack.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnBackMouseMoved(evt);
            }
        });
        pnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnBackMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quay lại");

        javax.swing.GroupLayout pnBackLayout = new javax.swing.GroupLayout(pnBack);
        pnBack.setLayout(pnBackLayout);
        pnBackLayout.setHorizontalGroup(
            pnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBackLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel4)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        pnBackLayout.setVerticalGroup(
            pnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBackLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/IS.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("-------- ***---------");

        javax.swing.GroupLayout pnChucNangLayout = new javax.swing.GroupLayout(pnChucNang);
        pnChucNang.setLayout(pnChucNangLayout);
        pnChucNangLayout.setHorizontalGroup(
            pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnThemTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnDoiMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnChucNangLayout.createSequentialGroup()
                .addGroup(pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnChucNangLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(pnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnChucNangLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnChucNangLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnChucNangLayout.setVerticalGroup(
            pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChucNangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(23, 23, 23)
                .addComponent(pnThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnDoiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(pnThemTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pnNen.setBackground(new java.awt.Color(51, 204, 255));

        pnThongTin2.setBackground(new java.awt.Color(0, 204, 255));
        pnThongTin2.setPreferredSize(new java.awt.Dimension(518, 483));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel28.setText("Họ tên:");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel29.setText("SĐT:");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel30.setText("Địa chỉ:");

        txtTen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtDiaChi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtSDT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        btCapNhatTK.setText("Cập nhật");
        btCapNhatTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCapNhatTKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnThongTin2Layout = new javax.swing.GroupLayout(pnThongTin2);
        pnThongTin2.setLayout(pnThongTin2Layout);
        pnThongTin2Layout.setHorizontalGroup(
            pnThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTin2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(pnThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel30)
                    .addComponent(jLabel29)
                    .addComponent(jLabel28))
                .addGap(54, 54, 54)
                .addGroup(pnThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTin2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCapNhatTK)
                .addGap(148, 148, 148))
        );
        pnThongTin2Layout.setVerticalGroup(
            pnThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTin2Layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addGroup(pnThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(pnThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(pnThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btCapNhatTK)
                .addGap(114, 114, 114))
        );

        pnDoiMatKhau2.setBackground(new java.awt.Color(0, 204, 255));
        pnDoiMatKhau2.setPreferredSize(new java.awt.Dimension(518, 483));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Mật khẩu cũ:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Mật khẩu mới:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Nhập lại mật khẩu mới:");

        btCapNhatMK.setText("Cập nhật");
        btCapNhatMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCapNhatMKActionPerformed(evt);
            }
        });

        txtMKCu.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N

        txtMKMoi.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N

        txtMKMoi2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N

        javax.swing.GroupLayout pnDoiMatKhau2Layout = new javax.swing.GroupLayout(pnDoiMatKhau2);
        pnDoiMatKhau2.setLayout(pnDoiMatKhau2Layout);
        pnDoiMatKhau2Layout.setHorizontalGroup(
            pnDoiMatKhau2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDoiMatKhau2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCapNhatMK)
                .addGap(123, 123, 123))
            .addGroup(pnDoiMatKhau2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnDoiMatKhau2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(pnDoiMatKhau2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMKCu, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMKMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMKMoi2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pnDoiMatKhau2Layout.setVerticalGroup(
            pnDoiMatKhau2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDoiMatKhau2Layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(pnDoiMatKhau2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtMKCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(pnDoiMatKhau2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtMKMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(pnDoiMatKhau2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtMKMoi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btCapNhatMK)
                .addGap(116, 116, 116))
        );

        pnThemTK2.setBackground(new java.awt.Color(0, 204, 255));
        pnThemTK2.setPreferredSize(new java.awt.Dimension(518, 483));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Họ tên:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("SĐT:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Địa chỉ:");

        txtTenAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtDiachiAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtSDTAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        btTaoTK.setText("Tạo tài khoản");
        btTaoTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTaoTKActionPerformed(evt);
            }
        });

        txtUserName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("UserName:");

        txtPass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Password:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Loại TK:");

        cbLoaiTK.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cbLoaiTK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản trị viên", "Thủ thư", "Nhân viên hỗ trợ đọc giả" }));

        javax.swing.GroupLayout pnThemTK2Layout = new javax.swing.GroupLayout(pnThemTK2);
        pnThemTK2.setLayout(pnThemTK2Layout);
        pnThemTK2Layout.setHorizontalGroup(
            pnThemTK2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThemTK2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pnThemTK2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnThemTK2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(54, 54, 54)
                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnThemTK2Layout.createSequentialGroup()
                        .addGroup(pnThemTK2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(54, 54, 54)
                        .addGroup(pnThemTK2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSDTAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiachiAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnThemTK2Layout.createSequentialGroup()
                        .addGroup(pnThemTK2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addGap(54, 54, 54)
                        .addGroup(pnThemTK2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPass)
                            .addComponent(cbLoaiTK, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThemTK2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btTaoTK)
                .addGap(156, 156, 156))
        );
        pnThemTK2Layout.setVerticalGroup(
            pnThemTK2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThemTK2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnThemTK2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTenAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnThemTK2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtSDTAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnThemTK2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtDiachiAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnThemTK2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pnThemTK2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThemTK2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cbLoaiTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btTaoTK)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnNenLayout = new javax.swing.GroupLayout(pnNen);
        pnNen.setLayout(pnNenLayout);
        pnNenLayout.setHorizontalGroup(
            pnNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnThongTin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnNenLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnDoiMatKhau2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(pnNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnNenLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnThemTK2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnNenLayout.setVerticalGroup(
            pnNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnThongTin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnNenLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnDoiMatKhau2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(pnNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnNenLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnThemTK2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnNen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnChucNang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnNen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnChucNangMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnChucNangMouseMoved
        resetColor(pnThongTin);
        resetColor(pnDoiMatKhau);
        resetColor(pnThemTK);
        resetColor(pnBack);
    }//GEN-LAST:event_pnChucNangMouseMoved

    private void pnThongTinMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnThongTinMouseMoved
        setColor(pnThongTin);// TODO add your handling code here:
    }//GEN-LAST:event_pnThongTinMouseMoved

    private void pnDoiMatKhauMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnDoiMatKhauMouseMoved
        setColor(pnDoiMatKhau);// TODO add your handling code here:
    }//GEN-LAST:event_pnDoiMatKhauMouseMoved

    private void pnThemTKMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnThemTKMouseMoved
        setColor(pnThemTK);// TODO add your handling code here:
    }//GEN-LAST:event_pnThemTKMouseMoved

    private void pnThongTinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnThongTinMousePressed
        pnThongTin2.setVisible(true);
        pnDoiMatKhau2.setVisible(false);
        pnThemTK2.setVisible(false);// TODO add your handling code here:
        loadPanelThongTin();
    }//GEN-LAST:event_pnThongTinMousePressed

    private void pnDoiMatKhauMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnDoiMatKhauMousePressed
        pnThongTin2.setVisible(false);
        pnDoiMatKhau2.setVisible(true);
        pnThemTK2.setVisible(false);
    }//GEN-LAST:event_pnDoiMatKhauMousePressed

    private void pnThemTKMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnThemTKMousePressed
       if(Acc.getLoaiTK().equals("1")){
           pnThongTin2.setVisible(false);
           pnDoiMatKhau2.setVisible(false);
           pnThemTK2.setVisible(true);// TODO add your handling code here:
       }
       else{
           JOptionPane.showMessageDialog(rootPane, "Chỉ quản trị viên mới mở được chức năng này!");
       }       
    }//GEN-LAST:event_pnThemTKMousePressed

    private void pnBackMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnBackMouseMoved
        setColor(pnBack);
    }//GEN-LAST:event_pnBackMouseMoved

    private void pnBackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnBackMousePressed
        jfMainMenu main = new jfMainMenu(Acc);
        main.setVisible(true);
        main.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_pnBackMousePressed

    private void btCapNhatMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCapNhatMKActionPerformed
        
        String cu = Acc.getPassWord();       
        
        if(!(cu.equals(txtMKCu.getText()))){
            JOptionPane.showMessageDialog(rootPane, "Mật khẩu cũ không đúng");
        }
        else{
            if(!txtMKMoi.getText().equals(txtMKMoi2.getText())){
                JOptionPane.showMessageDialog(rootPane, "Mật khẩu mới không khớp");
            }
            else{
                   AccountDAO.Instance().updatePassWord(Acc.getiD(), txtMKMoi2.getText());
                   JOptionPane.showMessageDialog(rootPane, "Thanh Cong!"); 
                   Acc = AccountDAO.Instance().getAcc(Acc.getUserName(), txtMKMoi2.getText());
                   txtMKCu.setText("");
                   txtMKMoi.setText("");
                   txtMKMoi2.setText("");                 
                }
        }
            
           
    }//GEN-LAST:event_btCapNhatMKActionPerformed

    private void btCapNhatTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCapNhatTKActionPerformed
        int dt = 0; 
        try {
            dt = Integer.parseInt(txtSDT.getText());
        } catch (Exception e) {
            dt=0;
        }
        
        if(txtTen.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Họ tên trống!");
        }
        else
            if(dt == 0 ){
                JOptionPane.showMessageDialog(rootPane, "SDT là 1 dãy số");
            }
            else{
                AccountDAO.Instance().updateThongTinTK(Acc.getiD(), txtTen.getText(),txtDiaChi.getText() , txtSDT.getText());
                Acc = AccountDAO.Instance().getAcc(Acc.getUserName(), Acc.getPassWord());
                loadPanelThongTin();
                JOptionPane.showMessageDialog(rootPane, "Thành công!");
            }
    }//GEN-LAST:event_btCapNhatTKActionPerformed

    private void btTaoTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTaoTKActionPerformed
        List<String> list = AccountDAO.Instance().getListUser();
        int kq = cbLoaiTK.getSelectedIndex();
        int dt = 0; 
        try {
            dt = Integer.parseInt(txtSDTAdd.getText());
        } catch (Exception e) {
            dt=0;
        }
        
        if(txtTenAdd.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Họ tên trống!");
        }
        else
            if(dt == 0 ){
                JOptionPane.showMessageDialog(rootPane, "SDT là 1 dãy số");
            }
            else
                if(list.contains(txtUserName.getText())){
                    JOptionPane.showMessageDialog(rootPane, "Username này đã có người sử dụng!");
                }
                else
                    if(txtPass.getText().equals(""))
                        JOptionPane.showMessageDialog(rootPane, "Nhập mật khẩu");
                    else {
                        AccountDAO.Instance().insertAccount(txtUserName.getText(), txtPass.getText(), txtTenAdd.getText(), kq+1, txtDiachiAdd.getText(), txtSDTAdd.getText());
                        JOptionPane.showMessageDialog(rootPane, "Thanh Cong!");
                        loadPanelThemTK();
                        
                    }
    }//GEN-LAST:event_btTaoTKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfAccount2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfAccount2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfAccount2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfAccount2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfAccount2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCapNhatMK;
    private javax.swing.JButton btCapNhatTK;
    private javax.swing.JButton btTaoTK;
    private javax.swing.JComboBox<String> cbLoaiTK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnBack;
    private javax.swing.JPanel pnChucNang;
    private javax.swing.JPanel pnDoiMatKhau;
    private javax.swing.JPanel pnDoiMatKhau2;
    private javax.swing.JPanel pnNen;
    private javax.swing.JPanel pnThemTK;
    private javax.swing.JPanel pnThemTK2;
    private javax.swing.JPanel pnThongTin;
    private javax.swing.JPanel pnThongTin2;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtDiachiAdd;
    private javax.swing.JPasswordField txtMKCu;
    private javax.swing.JPasswordField txtMKMoi;
    private javax.swing.JPasswordField txtMKMoi2;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtSDTAdd;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTenAdd;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
