/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.BaoCaoDAO;
import DTO.AccountDTO;
import DTO.BaoCaoDTO;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Hashtable;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author NCT
 */
public class jfBaoCao extends javax.swing.JFrame {
    
    protected  AccountDTO Acc;
    DefaultTableModel tabModel;
    /**
     * Creates new form jfBaoCao
     */
    public jfBaoCao() {
        initComponents();
        pnTheoThang.setVisible(false);
        tabModel = (DefaultTableModel) tableThongKe.getModel();
        tabModel.setColumnIdentifiers(new Object[]{"STT", "Mã đầu sách", "Tên đầu sách", "Số lượng mượn"});
    }
    
    public jfBaoCao(AccountDTO acc) {
        initComponents();
        Acc=acc;
        pnTheoThang.setVisible(false);
        tabModel = (DefaultTableModel) tableThongKe.getModel();
        tabModel.setColumnIdentifiers(new Object[]{"STT", "Mã đầu sách", "Tên đầu sách", "Số lượng mượn"});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnNen = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbLoaiBaoCao = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbLoaiThoiGian = new javax.swing.JComboBox<>();
        pnThoiGian = new javax.swing.JPanel();
        pnTheoNgay = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        dcTuNgay = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        dcDenNgay = new com.toedter.calendar.JDateChooser();
        pnTheoThang = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        mcThang = new com.toedter.calendar.JMonthChooser();
        ycNam = new com.toedter.calendar.JYearChooser();
        btXemBC = new javax.swing.JButton();
        btIn = new javax.swing.JButton();
        btBack = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableThongKe = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        pnNen.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("BÁO CÁO - THỐNG KÊ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(205, 205, 205))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(22, 22, 22))
        );

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 51, 0));
        jLabel2.setText("Chọn loại báo cáo: ");

        cbLoaiBaoCao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbLoaiBaoCao.setForeground(java.awt.Color.gray);
        cbLoaiBaoCao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thống kê số lượng sách mượn theo đầu sách", "Thống kê số lượng sách mượn theo đọc giả" }));
        cbLoaiBaoCao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbLoaiBaoCaoItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 51, 0));
        jLabel3.setText("Chọn thời gian:");

        cbLoaiThoiGian.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        cbLoaiThoiGian.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbLoaiThoiGian.setForeground(java.awt.Color.gray);
        cbLoaiThoiGian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theo ngày", "Theo tháng" }));
        cbLoaiThoiGian.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbLoaiThoiGianItemStateChanged(evt);
            }
        });

        pnThoiGian.setBackground(new java.awt.Color(102, 204, 255));

        pnTheoNgay.setBackground(new java.awt.Color(102, 204, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Từ ngày:");

        dcTuNgay.setBackground(java.awt.Color.pink);
        dcTuNgay.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        dcTuNgay.setDateFormatString("dd/MM/yyyy");
        dcTuNgay.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        dcTuNgay.setRequestFocusEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Đến ngày:");

        dcDenNgay.setBackground(java.awt.Color.pink);
        dcDenNgay.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        dcDenNgay.setDateFormatString("dd/MM/yyyy");
        dcDenNgay.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        dcDenNgay.setRequestFocusEnabled(false);

        javax.swing.GroupLayout pnTheoNgayLayout = new javax.swing.GroupLayout(pnTheoNgay);
        pnTheoNgay.setLayout(pnTheoNgayLayout);
        pnTheoNgayLayout.setHorizontalGroup(
            pnTheoNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTheoNgayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(31, 31, 31)
                .addComponent(dcTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(dcDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnTheoNgayLayout.setVerticalGroup(
            pnTheoNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTheoNgayLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(pnTheoNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(dcDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(24, 24, 24))
        );

        pnTheoThang.setBackground(new java.awt.Color(102, 204, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Tháng:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Năm:");

        mcThang.setBackground(java.awt.Color.orange);
        mcThang.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mcThang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mcThang.setMonth(12);
        mcThang.setName("MM"); // NOI18N

        ycNam.setBackground(java.awt.Color.orange);
        ycNam.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnTheoThangLayout = new javax.swing.GroupLayout(pnTheoThang);
        pnTheoThang.setLayout(pnTheoThangLayout);
        pnTheoThangLayout.setHorizontalGroup(
            pnTheoThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTheoThangLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(mcThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(30, 30, 30)
                .addComponent(ycNam, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        pnTheoThangLayout.setVerticalGroup(
            pnTheoThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTheoThangLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnTheoThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTheoThangLayout.createSequentialGroup()
                        .addGroup(pnTheoThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mcThang, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(ycNam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTheoThangLayout.createSequentialGroup()
                        .addGroup(pnTheoThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(34, 34, 34))))
        );

        javax.swing.GroupLayout pnThoiGianLayout = new javax.swing.GroupLayout(pnThoiGian);
        pnThoiGian.setLayout(pnThoiGianLayout);
        pnThoiGianLayout.setHorizontalGroup(
            pnThoiGianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 714, Short.MAX_VALUE)
            .addGroup(pnThoiGianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnThoiGianLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnTheoNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(pnThoiGianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnThoiGianLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(pnTheoThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(13, Short.MAX_VALUE)))
        );
        pnThoiGianLayout.setVerticalGroup(
            pnThoiGianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
            .addGroup(pnThoiGianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnThoiGianLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnTheoNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(pnThoiGianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnThoiGianLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnTheoThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        btXemBC.setBackground(java.awt.Color.cyan);
        btXemBC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btXemBC.setText("xem báo cáo");
        btXemBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXemBCActionPerformed(evt);
            }
        });

        btIn.setBackground(java.awt.Color.red);
        btIn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btIn.setText("IN");
        btIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInActionPerformed(evt);
            }
        });

        btBack.setBackground(java.awt.Color.white);
        btBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btBack.setText("Trở về");
        btBack.setActionCommand("");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbLoaiThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbLoaiBaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(pnThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btXemBC, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btIn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBack))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbLoaiBaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbLoaiThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btXemBC, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btIn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btBack, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tableThongKe.setBackground(java.awt.Color.yellow);
        tableThongKe.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tableThongKe.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tableThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableThongKe.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jScrollPane1.setViewportView(tableThongKe);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1035, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnNenLayout = new javax.swing.GroupLayout(pnNen);
        pnNen.setLayout(pnNenLayout);
        pnNenLayout.setHorizontalGroup(
            pnNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pnNenLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnNenLayout.setVerticalGroup(
            pnNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnNen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnNen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbLoaiThoiGianItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbLoaiThoiGianItemStateChanged
        int kq = cbLoaiThoiGian.getSelectedIndex();
        if(kq==0){
            pnTheoNgay.setVisible(true);
            pnTheoThang.setVisible(false);
        }
        else{
            pnTheoNgay.setVisible(false);
            pnTheoThang.setVisible(true);
        }
    }//GEN-LAST:event_cbLoaiThoiGianItemStateChanged

    private void btXemBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXemBCActionPerformed
        tabModel.setRowCount(0);
        int loaiBC = cbLoaiBaoCao.getSelectedIndex(), loaiTG = cbLoaiThoiGian.getSelectedIndex();
        List<BaoCaoDTO> list = null;
        
        if(loaiTG == 0){
            if(dcTuNgay.getDate()==null || dcDenNgay.getDate()==null){
                JOptionPane.showMessageDialog(rootPane, "Chọn khoảng thời gian!");
            }
            else{
                SimpleDateFormat d=new SimpleDateFormat("MM/dd/yyyy");
                String tuNgay = d.format(dcTuNgay.getDate());
                String denNgay = d.format(dcDenNgay.getDate());
                
                list = BaoCaoDAO.Instance().getTableBaoCao(loaiBC, loaiTG, tuNgay, denNgay, 0, 0);   
            }
        }
        
        if(loaiTG == 1){
                list = BaoCaoDAO.Instance().getTableBaoCao(loaiBC, loaiTG, null, null, mcThang.getMonth()+1, ycNam.getYear());
        }
        
        int i =1;
        
        if(loaiBC == 0){
            for (Iterator<BaoCaoDTO> it = list.iterator(); it.hasNext();) {
                BaoCaoDTO x = it.next();
                tabModel.addRow(new Object[]{
                    i++, x.getMaDS(),x.getTenDS(),x.getSlMuonDS()
                });
            }
        }else
            if(loaiBC==1){
                for (BaoCaoDTO x : list){
                    tabModel.addRow(new Object[]{
                        i++, x.getMaDG(),x.getTenDG(),x.getSlMuonDG()
                    });
                }
            }
     
    }//GEN-LAST:event_btXemBCActionPerformed

    private void cbLoaiBaoCaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbLoaiBaoCaoItemStateChanged
        int kq = cbLoaiBaoCao.getSelectedIndex();
        tabModel.setRowCount(0);
        if(kq==0){
            tabModel.setColumnIdentifiers(new Object[]{"STT", "Mã đầu sách", "Tên đầu sách", "Số lượng mượn"});
        }
        else{
            tabModel.setColumnIdentifiers(new Object[]{"STT", "Mã đọc giả", "Tên đọc giả", "Số lượng mượn"});
        }
    }//GEN-LAST:event_cbLoaiBaoCaoItemStateChanged

    private void btInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInActionPerformed
        int loaiBC = cbLoaiBaoCao.getSelectedIndex(), loaiTG = cbLoaiThoiGian.getSelectedIndex();
        Connection conn = BaoCaoDAO.Instance().getConn();
        JasperReport jr = null;
        Hashtable hash = new Hashtable();
//         try {
//            JasperReport jr = JasperCompileManager.compileReport("src/iReport/rpTheoDS_1.jrxml");
//            InputStream is = new FileInputStream("src/iReport/rpTheoDS_1.jasper");
//        } catch (JRException ex) {
//            Logger.getLogger(jfBaoCao.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (FileNotFoundException ex) {
//            Logger.getLogger(jfBaoCao.class.getName()).log(Level.SEVERE, null, ex);
//        }
        
        if(loaiBC == 0 && loaiTG==0){
            try {
                jr = JasperCompileManager.compileReport("src/iReport/rpTheoDS_1.jrxml");
            } catch (JRException ex) {
                Logger.getLogger(jfBaoCao.class.getName()).log(Level.SEVERE, null, ex);
            }
             SimpleDateFormat d=new SimpleDateFormat("MM/dd/yyyy");
             String tuNgay = d.format(dcTuNgay.getDate());
             String denNgay = d.format(dcDenNgay.getDate());
             hash.put("tuNgay",tuNgay);
             hash.put("denNgay", denNgay);
             hash.put("thoiGian", tuNgay+"  -  "+denNgay);
          
        }
        
        if(loaiBC == 0 && loaiTG==1){
            try {
                jr = JasperCompileManager.compileReport("src/iReport/rpTheoDS_2.jrxml");
            } catch (JRException ex) {
                Logger.getLogger(jfBaoCao.class.getName()).log(Level.SEVERE, null, ex);
            }
             
             hash.put("thang",mcThang.getMonth()+1);
             hash.put("nam", ycNam.getYear());
             hash.put("thoiGian", mcThang.getMonth()+1+"  -  "+ycNam.getYear());       
        }
        
        
        if(loaiBC == 1 && loaiTG==0){
            try {
                jr = JasperCompileManager.compileReport("src/iReport/rpTheoDG_1.jrxml");
            } catch (JRException ex) {
                Logger.getLogger(jfBaoCao.class.getName()).log(Level.SEVERE, null, ex);
            }
             SimpleDateFormat d=new SimpleDateFormat("MM/dd/yyyy");
             String tuNgay = d.format(dcTuNgay.getDate());
             String denNgay = d.format(dcDenNgay.getDate());
             hash.put("tuNgay",tuNgay);
             hash.put("denNgay", denNgay);
             hash.put("thoiGian", tuNgay+"  -  "+denNgay);
          
        }
        
        if(loaiBC == 1 && loaiTG==1){
            try {
                jr = JasperCompileManager.compileReport("src/iReport/rpTheoDG_2.jrxml");
            } catch (JRException ex) {
                Logger.getLogger(jfBaoCao.class.getName()).log(Level.SEVERE, null, ex);
            }
             
             hash.put("thang",mcThang.getMonth()+1);
             hash.put("nam", ycNam.getYear());
             hash.put("thoiGian", mcThang.getMonth()+1+"  -  "+ycNam.getYear());       
        }
        
        try {
            JasperPrint print = JasperFillManager.fillReport(jr, hash, conn);
            JasperViewer.viewReport(print);
            
        } catch (JRException ex) {
            Logger.getLogger(jfBaoCao.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btInActionPerformed

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        jfMainMenu home = new jfMainMenu(Acc);
                
        home.setVisible(true);
        home.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfBaoCao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfBaoCao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfBaoCao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfBaoCao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfBaoCao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btIn;
    private javax.swing.JButton btXemBC;
    private javax.swing.JComboBox<String> cbLoaiBaoCao;
    private javax.swing.JComboBox<String> cbLoaiThoiGian;
    private com.toedter.calendar.JDateChooser dcDenNgay;
    private com.toedter.calendar.JDateChooser dcTuNgay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JMonthChooser mcThang;
    private javax.swing.JPanel pnNen;
    private javax.swing.JPanel pnTheoNgay;
    private javax.swing.JPanel pnTheoThang;
    private javax.swing.JPanel pnThoiGian;
    private javax.swing.JTable tableThongKe;
    private com.toedter.calendar.JYearChooser ycNam;
    // End of variables declaration//GEN-END:variables
}
