/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.AccountDTO;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author NCT
 */
public class jfMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form jfMainMenu
     */
    
    protected AccountDTO Acc;

    
    public jfMainMenu() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public jfMainMenu(AccountDTO acc) {
        initComponents();
        setLocationRelativeTo(null);
        Acc = acc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnNen = new javax.swing.JPanel();
        pnTieuDe = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lbTieuDe = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btAccount = new javax.swing.JLabel();
        btDocGia = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btSach = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btMuonSach = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btTraSach = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btAboutUs = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        btThongKe = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        btLogout = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btExit = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        pnNen.setBackground(java.awt.Color.white);
        pnNen.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnNenMouseMoved(evt);
            }
        });

        pnTieuDe.setBackground(new java.awt.Color(51, 130, 255));
        pnTieuDe.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        lbTieuDe.setBackground(new java.awt.Color(255, 255, 255));
        lbTieuDe.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        lbTieuDe.setForeground(new java.awt.Color(255, 255, 255));
        lbTieuDe.setText("Phần Mềm Quản Lý Thư Viện");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/main.png"))); // NOI18N
        jLabel6.setMaximumSize(new java.awt.Dimension(283, 121));

        jPanel5.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        btAccount.setBackground(new java.awt.Color(0, 204, 255));
        btAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Acc.png"))); // NOI18N
        btAccount.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btAccountMouseMoved(evt);
            }
        });
        btAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btAccountMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnTieuDeLayout = new javax.swing.GroupLayout(pnTieuDe);
        pnTieuDe.setLayout(pnTieuDeLayout);
        pnTieuDeLayout.setHorizontalGroup(
            pnTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTieuDeLayout.createSequentialGroup()
                .addGroup(pnTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTieuDeLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lbTieuDe))
                    .addGroup(pnTieuDeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnTieuDeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btAccount))))
        );
        pnTieuDeLayout.setVerticalGroup(
            pnTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTieuDeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTieuDeLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTieuDeLayout.createSequentialGroup()
                        .addComponent(lbTieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
            .addGroup(pnTieuDeLayout.createSequentialGroup()
                .addComponent(btAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        btDocGia.setBackground(new java.awt.Color(51, 153, 255));
        btDocGia.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btDocGiaMouseMoved(evt);
            }
        });
        btDocGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btDocGiaMousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/member.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quản lí đọc giả");

        javax.swing.GroupLayout btDocGiaLayout = new javax.swing.GroupLayout(btDocGia);
        btDocGia.setLayout(btDocGiaLayout);
        btDocGiaLayout.setHorizontalGroup(
            btDocGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btDocGiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        btDocGiaLayout.setVerticalGroup(
            btDocGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btDocGiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btDocGiaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(26, 26, 26))
        );

        btSach.setBackground(new java.awt.Color(51, 153, 255));
        btSach.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btSachMouseMoved(evt);
            }
        });
        btSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btSachMousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/book.PNG"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quản lí sách");

        javax.swing.GroupLayout btSachLayout = new javax.swing.GroupLayout(btSach);
        btSach.setLayout(btSachLayout);
        btSachLayout.setHorizontalGroup(
            btSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btSachLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(40, 40, 40))
        );
        btSachLayout.setVerticalGroup(
            btSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btSachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btSachLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(31, 31, 31))
        );

        btMuonSach.setBackground(new java.awt.Color(51, 153, 255));
        btMuonSach.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btMuonSachMouseMoved(evt);
            }
        });
        btMuonSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btMuonSachMousePressed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/muonsach.PNG"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mượn");
        jLabel7.setPreferredSize(new java.awt.Dimension(139, 29));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("sách");
        jLabel8.setPreferredSize(new java.awt.Dimension(139, 29));

        javax.swing.GroupLayout btMuonSachLayout = new javax.swing.GroupLayout(btMuonSach);
        btMuonSach.setLayout(btMuonSachLayout);
        btMuonSachLayout.setHorizontalGroup(
            btMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btMuonSachLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(btMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
        btMuonSachLayout.setVerticalGroup(
            btMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btMuonSachLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btTraSach.setBackground(new java.awt.Color(51, 153, 255));
        btTraSach.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btTraSachMouseMoved(evt);
            }
        });
        btTraSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btTraSachMousePressed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/TraSach.PNG"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Trả");
        jLabel12.setPreferredSize(new java.awt.Dimension(139, 29));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("sách");
        jLabel13.setPreferredSize(new java.awt.Dimension(139, 29));

        javax.swing.GroupLayout btTraSachLayout = new javax.swing.GroupLayout(btTraSach);
        btTraSach.setLayout(btTraSachLayout);
        btTraSachLayout.setHorizontalGroup(
            btTraSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btTraSachLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(btTraSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(52, 52, 52))
        );
        btTraSachLayout.setVerticalGroup(
            btTraSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btTraSachLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btTraSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        btAboutUs.setBackground(new java.awt.Color(51, 153, 255));
        btAboutUs.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btAboutUsMouseMoved(evt);
            }
        });
        btAboutUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btAboutUsMousePressed(evt);
            }
        });

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/aboutUS.png"))); // NOI18N

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("About US");

        javax.swing.GroupLayout btAboutUsLayout = new javax.swing.GroupLayout(btAboutUs);
        btAboutUs.setLayout(btAboutUsLayout);
        btAboutUsLayout.setHorizontalGroup(
            btAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btAboutUsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addGap(37, 37, 37)
                .addComponent(jLabel28)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        btAboutUsLayout.setVerticalGroup(
            btAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btAboutUsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btAboutUsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addGap(49, 49, 49))
        );

        btThongKe.setBackground(new java.awt.Color(51, 153, 255));
        btThongKe.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btThongKeMouseMoved(evt);
            }
        });
        btThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btThongKeMousePressed(evt);
            }
        });

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ThongKe.PNG"))); // NOI18N

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Xem thống kê");

        javax.swing.GroupLayout btThongKeLayout = new javax.swing.GroupLayout(btThongKe);
        btThongKe.setLayout(btThongKeLayout);
        btThongKeLayout.setHorizontalGroup(
            btThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btThongKeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btThongKeLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addGap(21, 21, 21))
        );
        btThongKeLayout.setVerticalGroup(
            btThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btThongKeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addGap(26, 26, 26)
                .addComponent(jLabel26)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        btLogout.setBackground(new java.awt.Color(51, 153, 255));
        btLogout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btLogoutMouseMoved(evt);
            }
        });
        btLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btLogoutMousePressed(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logout.PNG"))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Logout");

        javax.swing.GroupLayout btLogoutLayout = new javax.swing.GroupLayout(btLogout);
        btLogout.setLayout(btLogoutLayout);
        btLogoutLayout.setHorizontalGroup(
            btLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(55, 55, 55))
        );
        btLogoutLayout.setVerticalGroup(
            btLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        btExit.setBackground(new java.awt.Color(51, 153, 255));
        btExit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btExitMouseMoved(evt);
            }
        });
        btExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btExitMousePressed(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/exit.PNG"))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Exit");

        javax.swing.GroupLayout btExitLayout = new javax.swing.GroupLayout(btExit);
        btExit.setLayout(btExitLayout);
        btExitLayout.setHorizontalGroup(
            btExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(69, 69, 69))
        );
        btExitLayout.setVerticalGroup(
            btExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btExitLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnNenLayout = new javax.swing.GroupLayout(pnNen);
        pnNen.setLayout(pnNenLayout);
        pnNenLayout.setHorizontalGroup(
            pnNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnNenLayout.createSequentialGroup()
                        .addComponent(btDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btMuonSach, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btTraSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnNenLayout.createSequentialGroup()
                        .addComponent(btAboutUs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(pnNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addComponent(pnTieuDe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnNenLayout.setVerticalGroup(
            pnNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNenLayout.createSequentialGroup()
                .addComponent(pnTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btMuonSach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btTraSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btDocGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(pnNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnNenLayout.createSequentialGroup()
                        .addComponent(btLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btAboutUs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnNen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnNen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1008, 535);
    }// </editor-fold>//GEN-END:initComponents

    private void btDocGiaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDocGiaMouseMoved
        setColor(btDocGia);
    }//GEN-LAST:event_btDocGiaMouseMoved

    private void btSachMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSachMouseMoved
        setColor(btSach);
    }//GEN-LAST:event_btSachMouseMoved

    private void btMuonSachMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMuonSachMouseMoved
          setColor(btMuonSach);
    }//GEN-LAST:event_btMuonSachMouseMoved

    private void btTraSachMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btTraSachMouseMoved
          setColor(btTraSach);
    }//GEN-LAST:event_btTraSachMouseMoved

    private void btAboutUsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAboutUsMouseMoved
               setColor(btAboutUs);
    }//GEN-LAST:event_btAboutUsMouseMoved

    private void btThongKeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btThongKeMouseMoved
         setColor(btThongKe);
    }//GEN-LAST:event_btThongKeMouseMoved

    private void btLogoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLogoutMouseMoved
         setColor(btLogout);
    }//GEN-LAST:event_btLogoutMouseMoved

    private void btExitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExitMouseMoved
         setColor(btExit);
    }//GEN-LAST:event_btExitMouseMoved

    
    
    private void pnNenMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnNenMouseMoved
        resetColor(btDocGia);
        resetColor(btMuonSach);
        resetColor(btTraSach);
        resetColor(btLogout);
        resetColor(btExit);
        resetColor(btThongKe); 
        resetColor(btSach);
        resetColor(btAboutUs);
        btAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Acc.png")));
    }//GEN-LAST:event_pnNenMouseMoved

    private void btExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExitMousePressed
        System.exit(0);
    }//GEN-LAST:event_btExitMousePressed

    private void btMuonSachMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMuonSachMousePressed
        if(Acc.getLoaiTK().equals("3")){
           JOptionPane.showMessageDialog(rootPane, "Bạn không có quyền mở chức năng này!");
       } 
        else{
        jfMuonSach3 ms = new jfMuonSach3(Acc);               
        ms.setVisible(true);
        ms.setLocationRelativeTo(null);
        this.dispose();
        }
    }//GEN-LAST:event_btMuonSachMousePressed

    private void btTraSachMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btTraSachMousePressed
        if(Acc.getLoaiTK().equals("3")){
           JOptionPane.showMessageDialog(rootPane, "Bạn không có quyền mở chức năng này!");
       } 
        else{
        jfTraSach ts = new jfTraSach(Acc);
        ts.setVisible(true);
        ts.setLocationRelativeTo(null);
        this.dispose();
        }
    }//GEN-LAST:event_btTraSachMousePressed

    private void btSachMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSachMousePressed
        if(Acc.getLoaiTK().equals("3")){
           JOptionPane.showMessageDialog(rootPane, "Bạn không được quyền mở chức năng này!");
       }
        else{
        QLSach2 s = new QLSach2(Acc);
        s.setVisible(true);
        s.setLocationRelativeTo(null);
        this.dispose();
        }
        
        
    }//GEN-LAST:event_btSachMousePressed

    private void btLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLogoutMousePressed
        jfLogin l = new jfLogin();
        l.setVisible(true);
        l.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btLogoutMousePressed

    private void btAboutUsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAboutUsMousePressed
        jfAboutUs a = new jfAboutUs();
        a.setVisible(true);
        a.setLocationRelativeTo(null);
    }//GEN-LAST:event_btAboutUsMousePressed

    private void btAccountMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAccountMouseMoved
        btAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Acc_color.png")));
    }//GEN-LAST:event_btAccountMouseMoved

    private void btAccountMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAccountMousePressed
        jfAccount2 ac = new jfAccount2(Acc);
        ac.setVisible(true);
        ac.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btAccountMousePressed

    private void btThongKeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btThongKeMousePressed
        if(!Acc.getLoaiTK().equals("1")){
           JOptionPane.showMessageDialog(rootPane, "Chỉ quản trị viên mới mở được chức năng này!");
       }
        else{
            jfBaoCao bc = new jfBaoCao(Acc);
            bc.setVisible(true);
            bc.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_btThongKeMousePressed

    private void btDocGiaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDocGiaMousePressed
        if(Acc.getLoaiTK().equals("2")){
           JOptionPane.showMessageDialog(rootPane, "Bạn không có quyền mở chức năng này!");
       }
        else{
        JfDocGia s = new JfDocGia(Acc);
        s.setVisible(true);
        s.setLocationRelativeTo(null);
        this.dispose();
        }
    }//GEN-LAST:event_btDocGiaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfMainMenu().setVisible(true);
            }
        });
    }

    void setColor(JPanel pn){
        pn.setBackground(new Color(0,204,255));
    }
    
    void resetColor(JPanel pn){
        pn.setBackground(new Color(51,153,255));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btAboutUs;
    private javax.swing.JLabel btAccount;
    private javax.swing.JPanel btDocGia;
    private javax.swing.JPanel btExit;
    private javax.swing.JPanel btLogout;
    private javax.swing.JPanel btMuonSach;
    private javax.swing.JPanel btSach;
    private javax.swing.JPanel btThongKe;
    private javax.swing.JPanel btTraSach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbTieuDe;
    private javax.swing.JPanel pnNen;
    private javax.swing.JPanel pnTieuDe;
    // End of variables declaration//GEN-END:variables
}
