/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.MuonSachDAO;
import DTO.AccountDTO;
import DTO.MuonSachDTO;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NCT
 */
public class jfMuonSach3 extends javax.swing.JFrame {

  //  private ArrayList<MuonSachDTO> listMuon = new ArrayList<>();
  //  private ArrayList<String> listMaCSMuon = new ArrayList<>();
    protected AccountDTO Acc;
    private int soSachDangMuon ;
    private String maDG;
    
    public jfMuonSach3() {
        initComponents();
        loadjfMuonSach2();
        setLocationRelativeTo(null);
    }
    
        public jfMuonSach3(AccountDTO acc) {
        initComponents();
        loadjfMuonSach2();
        setLocationRelativeTo(null);
        Acc = acc;
    }
    
    
    
    private void loadjfMuonSach2(){
        lbHoTen.setText("");
        lbNgaySinh.setText(null);
        lbDiaChi.setText(null);
        lbTichDiem.setText(null);
        lbDangMuon.setText(null);
        lbQuaHan.setText(null);
        lbAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/NonAva.png"))); // NOI18N      
        lbMemberType.setIcon(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMuonSach2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btQuetDG = new javax.swing.JButton();
        txtMaDG = new javax.swing.JTextField();
        lbCheckMaDG = new javax.swing.JLabel();
        lbHoTen = new javax.swing.JLabel();
        lbNgaySinh = new javax.swing.JLabel();
        lbDangMuon = new javax.swing.JLabel();
        lbTichDiem = new javax.swing.JLabel();
        lbQuaHan = new javax.swing.JLabel();
        lbAvatar = new javax.swing.JLabel();
        lbHoTen1 = new javax.swing.JLabel();
        lbNgaySinh1 = new javax.swing.JLabel();
        lbDangMuon1 = new javax.swing.JLabel();
        lbTichDiem1 = new javax.swing.JLabel();
        lbQuaHan1 = new javax.swing.JLabel();
        lbMemberType = new javax.swing.JLabel();
        lbDiaChi1 = new javax.swing.JLabel();
        lbDiaChi = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtMaCSTimKiem = new javax.swing.JTextField();
        btQuetSach = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableThongTinSachMuon = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        DS_SachMuon = new javax.swing.JScrollPane();
        jTextAreaMS = new javax.swing.JTextArea();
        btBack = new javax.swing.JButton();
        btThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 255));
        setUndecorated(true);
        setResizable(false);

        pnMuonSach2.setBackground(new java.awt.Color(255, 255, 255));
        pnMuonSach2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnMuonSach2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnMuonSach2MouseMoved(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 204, 255));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 39)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 255));
        jLabel3.setText("QUẢN LÝ MƯỢN SÁCH");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(411, 411, 411))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(java.awt.SystemColor.activeCaption);
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), new java.awt.Color(0, 102, 102)), "Thông tin đọc giả", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(0, 153, 102))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 51, 0));
        jLabel2.setText("Mã đọc giả");

        btQuetDG.setBackground(new java.awt.Color(0, 153, 255));
        btQuetDG.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btQuetDG.setForeground(new java.awt.Color(255, 255, 255));
        btQuetDG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/blue.png"))); // NOI18N
        btQuetDG.setText("Quét thẻ ĐG");
        btQuetDG.setToolTipText("");
        btQuetDG.setBorder(null);
        btQuetDG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btQuetDG.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btQuetDGMouseMoved(evt);
            }
        });
        btQuetDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuetDGActionPerformed(evt);
            }
        });

        txtMaDG.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        txtMaDG.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbCheckMaDG.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbCheckMaDG.setForeground(new java.awt.Color(204, 0, 0));

        lbHoTen.setFont(new java.awt.Font("Tahoma", 0, 27)); // NOI18N
        lbHoTen.setForeground(new java.awt.Color(0, 102, 102));
        lbHoTen.setText("Họ tên");

        lbNgaySinh.setFont(new java.awt.Font("Tahoma", 0, 27)); // NOI18N
        lbNgaySinh.setForeground(new java.awt.Color(0, 102, 102));
        lbNgaySinh.setText("Ngày sinh");

        lbDangMuon.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lbDangMuon.setForeground(new java.awt.Color(255, 255, 255));
        lbDangMuon.setText("Số sách đang mượn");

        lbTichDiem.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lbTichDiem.setForeground(new java.awt.Color(255, 255, 0));
        lbTichDiem.setText("Tích điểm");

        lbQuaHan.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lbQuaHan.setForeground(new java.awt.Color(255, 51, 0));
        lbQuaHan.setText("Số sách hanj");
        lbQuaHan.setToolTipText("");

        lbAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/NonAva.png"))); // NOI18N

        lbHoTen1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbHoTen1.setText("Họ tên:");
        lbHoTen1.setToolTipText("");

        lbNgaySinh1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbNgaySinh1.setText("Ngày sinh:");

        lbDangMuon1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbDangMuon1.setText("Số sách đang mượn:");

        lbTichDiem1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTichDiem1.setText("Tích điểm:");
        lbTichDiem1.setToolTipText("");

        lbQuaHan1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbQuaHan1.setText("Số sách quá hạn:");

        lbMemberType.setText(" ");

        lbDiaChi1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbDiaChi1.setText("Địa chỉ:");
        lbDiaChi1.setToolTipText("");

        lbDiaChi.setBackground(java.awt.SystemColor.activeCaption);
        lbDiaChi.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        lbDiaChi.setForeground(new java.awt.Color(0, 102, 102));
        lbDiaChi.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        lbDiaChi.setText("Địa chỉ");
        lbDiaChi.setAlignmentX(0.0F);
        lbDiaChi.setAlignmentY(0.0F);
        lbDiaChi.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btQuetDG, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtMaDG, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64)
                .addComponent(lbAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbMemberType, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNgaySinh1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbHoTen1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNgaySinh)
                            .addComponent(lbHoTen))
                        .addGap(158, 158, 158)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTichDiem1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbDangMuon1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(lbDiaChi1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbDiaChi)
                        .addGap(18, 18, 18)
                        .addComponent(lbQuaHan1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbQuaHan)
                    .addComponent(lbDangMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTichDiem))
                .addGap(173, 173, 173)
                .addComponent(lbCheckMaDG))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbHoTen1)
                            .addComponent(lbHoTen)
                            .addComponent(lbTichDiem1)
                            .addComponent(lbTichDiem))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNgaySinh1)
                            .addComponent(lbNgaySinh)
                            .addComponent(lbDangMuon)
                            .addComponent(lbDangMuon1))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbQuaHan1)
                            .addComponent(lbQuaHan)
                            .addComponent(lbDiaChi1)
                            .addComponent(lbDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(lbCheckMaDG)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMaDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btQuetDG, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMemberType)
                            .addComponent(lbAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34))
        );

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153)), "Thông tin sách mượn", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(0, 153, 102))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 51, 0));
        jLabel10.setText("Mã sách");

        txtMaCSTimKiem.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        txtMaCSTimKiem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btQuetSach.setBackground(new java.awt.Color(0, 153, 255));
        btQuetSach.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btQuetSach.setForeground(new java.awt.Color(255, 255, 255));
        btQuetSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/blue.png"))); // NOI18N
        btQuetSach.setText("Quét sách");
        btQuetSach.setToolTipText("");
        btQuetSach.setBorder(null);
        btQuetSach.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btQuetSach.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btQuetSachMouseMoved(evt);
            }
        });
        btQuetSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuetSachActionPerformed(evt);
            }
        });

        tableThongTinSachMuon.setBackground(new java.awt.Color(204, 255, 204));
        tableThongTinSachMuon.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 153, 0), null));
        tableThongTinSachMuon.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tableThongTinSachMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sách", "Tên sách", "Ngôn ngữ", "Tái bản", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableThongTinSachMuon.setRowHeight(29);
        jScrollPane1.setViewportView(tableThongTinSachMuon);
        if (tableThongTinSachMuon.getColumnModel().getColumnCount() > 0) {
            tableThongTinSachMuon.getColumnModel().getColumn(1).setMinWidth(350);
            tableThongTinSachMuon.getColumnModel().getColumn(2).setMinWidth(120);
            tableThongTinSachMuon.getColumnModel().getColumn(3).setMinWidth(70);
            tableThongTinSachMuon.getColumnModel().getColumn(4).setMinWidth(170);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), new java.awt.Color(0, 153, 102), null, null), "Lịch sử quét", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jTextAreaMS.setColumns(20);
        jTextAreaMS.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jTextAreaMS.setRows(5);
        DS_SachMuon.setViewportView(jTextAreaMS);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(DS_SachMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 884, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DS_SachMuon, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btQuetSach, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(91, 91, 91)
                            .addComponent(jLabel10))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(txtMaCSTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaCSTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btQuetSach, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/back.png"))); // NOI18N
        btBack.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btBackMouseMoved(evt);
            }
        });
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        btThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Thoat.png"))); // NOI18N
        btThoat.setToolTipText("");
        btThoat.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btThoatMouseMoved(evt);
            }
        });
        btThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnMuonSach2Layout = new javax.swing.GroupLayout(pnMuonSach2);
        pnMuonSach2.setLayout(pnMuonSach2Layout);
        pnMuonSach2Layout.setHorizontalGroup(
            pnMuonSach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnMuonSach2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnMuonSach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnMuonSach2Layout.createSequentialGroup()
                        .addComponent(btBack, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnMuonSach2Layout.createSequentialGroup()
                        .addGroup(pnMuonSach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnMuonSach2Layout.setVerticalGroup(
            pnMuonSach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMuonSach2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnMuonSach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBack, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMuonSach2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMuonSach2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btQuetDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuetDGActionPerformed
        String tenDG = null; String sachDangMuon=null; String sachQuaHan=null; String ngaySinh=null;String diaChi=null;String tichDiem=null;String gioiTinh=null;String loaiDG=null;
        maDG = txtMaDG.getText();
        try {
            tenDG = MuonSachDAO.Instance().getTenDG(txtMaDG.getText());
            //if(tenDG==null) System.out.println("MaDG SAI!");
        } catch (SQLException ex) {
            System.out.println("Loi button KtraDG");
        }

        if(tenDG==null) {
            loadjfMuonSach2();
            JOptionPane.showMessageDialog(rootPane, "MaDG không tồn tại!\n ");
        }else
        {
            ngaySinh = MuonSachDAO.Instance().getNgaySinh(txtMaDG.getText());
            diaChi = MuonSachDAO.Instance().getDiaChi(maDG);
            tichDiem = MuonSachDAO.Instance().getTichDiem(maDG);
            sachDangMuon = MuonSachDAO.Instance().getSLSachDangMuon(txtMaDG.getText());
            sachQuaHan = MuonSachDAO.Instance().getSLSachQuaHan(txtMaDG.getText());
            gioiTinh = MuonSachDAO.Instance().getGioiTinh(maDG);
            loaiDG = MuonSachDAO.Instance().getLoaiDG(maDG);

            lbHoTen.setText(tenDG);
            lbNgaySinh.setText(ngaySinh);
            lbDiaChi.setText(diaChi);
            lbTichDiem.setText(tichDiem);
            lbDangMuon.setText(sachDangMuon);
            lbQuaHan.setText(sachQuaHan);
            soSachDangMuon = Integer.parseInt(sachDangMuon);

            if(gioiTinh.equals("Nam")){
                lbAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/AvaNam.png"))); // NOI18N
            }
            else if(gioiTinh.equals("Nữ")){
                lbAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/AvaNu.png"))); // NOI18N
            }

            switch (loaiDG) {
                case "1":
                lbMemberType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/NEWmember.png"))); // NOI18N
                break;
                case "2":
                lbMemberType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/member2.png"))); // NOI18N
                break;
                case "3":
                lbMemberType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/VIPmember.png"))); // NOI18N
                break;
            }
        }
    }//GEN-LAST:event_btQuetDGActionPerformed

    private void btQuetSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuetSachActionPerformed
                           
        if(lbHoTen.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Quét thẻ đọc giả trước!");
        } 
        else{
            if(soSachDangMuon >= MuonSachDAO.Instance().getSoSachMuonToiDa(maDG)){
                JOptionPane.showMessageDialog(null, "Đã quá số sách tối đa được mượn!\n");
            }
            else{
                String trangThai = MuonSachDAO.Instance().getTrangThai(txtMaCSTimKiem.getText());

                String kq = null;
                if(trangThai == null){

                    JOptionPane.showMessageDialog(rootPane, "MaCS không tồn tại! \n Thử lại!");
                }
                else{
                    if(trangThai.equals("Không được mượn")){
                        kq="Không mượn được!";
                        JOptionPane.showMessageDialog(rootPane, "Sách này chỉ được phép đọc tại thư viện! \n Chọn cuốn khác!");
                    }
                    else{
                        if(trangThai.equals("Sẵn sàng")){
                            MuonSachDAO.Instance().insertMuonSach(maDG, txtMaCSTimKiem.getText());
                            JOptionPane.showMessageDialog(rootPane, "Mượn thành công!");
                            kq="Mượn thành công!";
                            btQuetDGActionPerformed(evt);

                        }
                    }
                    DefaultTableModel tabModel = (DefaultTableModel) tableThongTinSachMuon.getModel();
                    tabModel.setRowCount(0);
                    MuonSachDTO ms  = MuonSachDAO.Instance().getThongTinCSMuon(txtMaCSTimKiem.getText());
                    tabModel.addRow(new Object[]{
                                ms.getMaCS(), ms.getTenCS(), ms.getNgonNgu(), ms.getTaiBan(), ms.getTrangThai()
                            });
                    txtMaCSTimKiem.setText("");
                    String str =jTextAreaMS.getText()+ ms.getMaCS()+"\t"+ms.getTenCS()+"\t\t"+kq+"\n";
                    jTextAreaMS.setText(str); 
                    
                }
            }
        }
        
          
    }//GEN-LAST:event_btQuetSachActionPerformed

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        jfMainMenu home = new jfMainMenu(Acc);

        home.setVisible(true);
        home.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btBackActionPerformed

    private void btThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btThoatActionPerformed

    private void btBackMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBackMouseMoved
          btBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/back_2.png")));// TODO add your handling code here:
    }//GEN-LAST:event_btBackMouseMoved

    private void btThoatMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btThoatMouseMoved
         btThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Thoat_2.png")));// TODO add your handling code here:
    }//GEN-LAST:event_btThoatMouseMoved

    private void pnMuonSach2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMuonSach2MouseMoved
         btBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/back.png")));
         btThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Thoat.png")));
         btQuetDG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/blue.png")));
         btQuetSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/blue.png")));

    }//GEN-LAST:event_pnMuonSach2MouseMoved

    private void btQuetDGMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btQuetDGMouseMoved
         btQuetDG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/blue_2.png")));
    }//GEN-LAST:event_btQuetDGMouseMoved

    private void btQuetSachMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btQuetSachMouseMoved
        btQuetSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/blue_2.png")));// TODO add your handling code here:
    }//GEN-LAST:event_btQuetSachMouseMoved

    
    

    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(() -> {
            new jfMuonSach3().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane DS_SachMuon;
    private javax.swing.JButton btBack;
    private javax.swing.JButton btQuetDG;
    private javax.swing.JButton btQuetSach;
    private javax.swing.JButton btThoat;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaMS;
    private javax.swing.JLabel lbAvatar;
    private javax.swing.JLabel lbCheckMaDG;
    private javax.swing.JLabel lbDangMuon;
    private javax.swing.JLabel lbDangMuon1;
    private javax.swing.JTextField lbDiaChi;
    private javax.swing.JLabel lbDiaChi1;
    private javax.swing.JLabel lbHoTen;
    private javax.swing.JLabel lbHoTen1;
    private javax.swing.JLabel lbMemberType;
    private javax.swing.JLabel lbNgaySinh;
    private javax.swing.JLabel lbNgaySinh1;
    private javax.swing.JLabel lbQuaHan;
    private javax.swing.JLabel lbQuaHan1;
    private javax.swing.JLabel lbTichDiem;
    private javax.swing.JLabel lbTichDiem1;
    private javax.swing.JPanel pnMuonSach2;
    private javax.swing.JTable tableThongTinSachMuon;
    private javax.swing.JTextField txtMaCSTimKiem;
    private javax.swing.JTextField txtMaDG;
    // End of variables declaration//GEN-END:variables
}
