/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.MuonSachDAO;
import DAO.TraSachDAO;
import DTO.AccountDTO;
import DTO.TraSachDTO;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author NCT
 */
public class jfTraSach extends javax.swing.JFrame {

    /**
     * Creates new form jfTraSach
     */
    public jfTraSach() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public jfTraSach(AccountDTO acc) {
        initComponents();
        setLocationRelativeTo(null);
        Acc = acc;
    }

    protected AccountDTO Acc;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTraSach = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnTacVu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btQuetDG = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtMaDG = new javax.swing.JTextField();
        txtMaSach = new javax.swing.JTextField();
        btTraSach = new javax.swing.JButton();
        btGiaHan = new javax.swing.JButton();
        btMatSach = new javax.swing.JButton();
        lbTichDiem = new javax.swing.JLabel();
        pnDSMuon = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableThongTinSachMuon = new javax.swing.JTable();
        btBack = new javax.swing.JButton();
        btThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);

        pnTraSach.setBackground(new java.awt.Color(255, 255, 255));
        pnTraSach.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnTraSach.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnTraSachMouseMoved(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("Quản lý trả sách");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnTacVu.setBackground(java.awt.SystemColor.activeCaption);
        pnTacVu.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), new java.awt.Color(0, 153, 153)));
        pnTacVu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnTacVuMouseMoved(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setText("Mã đọc giả");

        btQuetDG.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btQuetDG.setForeground(new java.awt.Color(255, 255, 255));
        btQuetDG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/blue.png"))); // NOI18N
        btQuetDG.setText("Quét thẻ ĐG");
        btQuetDG.setToolTipText("");
        btQuetDG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btQuetDG.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btQuetDGMouseMoved(evt);
            }
        });
        btQuetDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuetDGActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 0));
        jLabel3.setText("Mã sách");

        txtMaDG.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        txtMaDG.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtMaSach.setBackground(new java.awt.Color(255, 255, 204));
        txtMaSach.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtMaSach.setForeground(new java.awt.Color(0, 102, 102));
        txtMaSach.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));
        txtMaSach.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtMaSachMouseMoved(evt);
            }
        });

        btTraSach.setBackground(new java.awt.Color(0, 153, 255));
        btTraSach.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btTraSach.setForeground(new java.awt.Color(255, 255, 255));
        btTraSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/blue.png"))); // NOI18N
        btTraSach.setText("Trả sách");
        btTraSach.setToolTipText("");
        btTraSach.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btTraSach.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btTraSachMouseMoved(evt);
            }
        });
        btTraSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTraSachActionPerformed(evt);
            }
        });

        btGiaHan.setBackground(new java.awt.Color(0, 153, 255));
        btGiaHan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btGiaHan.setForeground(new java.awt.Color(255, 255, 255));
        btGiaHan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/blue.png"))); // NOI18N
        btGiaHan.setText("Gia hạn");
        btGiaHan.setToolTipText("");
        btGiaHan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btGiaHan.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btGiaHanMouseMoved(evt);
            }
        });
        btGiaHan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGiaHanActionPerformed(evt);
            }
        });

        btMatSach.setBackground(new java.awt.Color(0, 153, 255));
        btMatSach.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btMatSach.setForeground(new java.awt.Color(255, 255, 255));
        btMatSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/blue.png"))); // NOI18N
        btMatSach.setText("Báo mất sách");
        btMatSach.setToolTipText("");
        btMatSach.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btMatSach.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btMatSachMouseMoved(evt);
            }
        });
        btMatSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMatSachActionPerformed(evt);
            }
        });

        lbTichDiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout pnTacVuLayout = new javax.swing.GroupLayout(pnTacVu);
        pnTacVu.setLayout(pnTacVuLayout);
        pnTacVuLayout.setHorizontalGroup(
            pnTacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTacVuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnTacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMaSach, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtMaDG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                        .addComponent(btGiaHan, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(pnTacVuLayout.createSequentialGroup()
                            .addComponent(lbTichDiem)
                            .addGap(18, 18, 18)
                            .addComponent(btTraSach, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btMatSach, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(btQuetDG, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        pnTacVuLayout.setVerticalGroup(
            pnTacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTacVuLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMaDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btQuetDG, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(pnTacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btTraSach, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTichDiem))
                .addGap(18, 18, 18)
                .addComponent(btGiaHan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btMatSach, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pnDSMuon.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), new java.awt.Color(0, 204, 204)), "Danh sách sách đang được mượn", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 153, 153))); // NOI18N
        pnDSMuon.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnDSMuonMouseMoved(evt);
            }
        });

        tableThongTinSachMuon.setBackground(new java.awt.Color(0, 204, 204));
        tableThongTinSachMuon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 1, true));
        tableThongTinSachMuon.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tableThongTinSachMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phiếu mượn", "Mã sách", "Tên sách", "Ngày mượn", "Ngày hết hạn", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableThongTinSachMuon.setRowHeight(29);
        tableThongTinSachMuon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableThongTinSachMuonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableThongTinSachMuon);
        if (tableThongTinSachMuon.getColumnModel().getColumnCount() > 0) {
            tableThongTinSachMuon.getColumnModel().getColumn(0).setMinWidth(40);
            tableThongTinSachMuon.getColumnModel().getColumn(2).setMinWidth(250);
        }

        javax.swing.GroupLayout pnDSMuonLayout = new javax.swing.GroupLayout(pnDSMuon);
        pnDSMuon.setLayout(pnDSMuonLayout);
        pnDSMuonLayout.setHorizontalGroup(
            pnDSMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDSMuonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 942, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        pnDSMuonLayout.setVerticalGroup(
            pnDSMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDSMuonLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/back.png"))); // NOI18N
        btBack.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btBackMouseMoved(evt);
            }
        });
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        btThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Thoat.png"))); // NOI18N
        btThoat.setToolTipText("");
        btThoat.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btThoatMouseMoved(evt);
            }
        });
        btThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnTraSachLayout = new javax.swing.GroupLayout(pnTraSach);
        pnTraSach.setLayout(pnTraSachLayout);
        pnTraSachLayout.setHorizontalGroup(
            pnTraSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnTraSachLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTraSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTraSachLayout.createSequentialGroup()
                        .addComponent(pnTacVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnDSMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnTraSachLayout.createSequentialGroup()
                        .addComponent(btBack, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnTraSachLayout.setVerticalGroup(
            pnTraSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTraSachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnTraSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnTacVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnDSMuon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnTraSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btThoat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTraSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTraSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void setColor(JButton pn){
        pn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/blue_2.png")));
    }
    
    void resetColor(JButton pn){
        pn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/blue.png")));
    }
    
    
    
    private void btTraSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTraSachActionPerformed
        if(txtMaSach.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Chọn sách cần trả! \n");
        }
        else{
            String kq = TraSachDAO.Instance().isQuaHan(txtMaDG.getText(), txtMaSach.getText());
            if (kq.equals("1")){
                lbTichDiem.setText("-10đ");
                lbTichDiem.setForeground(new java.awt.Color(255, 51, 51));
            }
            else{
                lbTichDiem.setText("+5đ");
                lbTichDiem.setForeground(new java.awt.Color(255, 255, 0));

            }
            TraSachDAO.Instance().TraSach(txtMaDG.getText(), txtMaSach.getText());
            btQuetDGActionPerformed(evt);
            txtMaSach.setText("");
        }
    }//GEN-LAST:event_btTraSachActionPerformed

    private void btGiaHanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGiaHanActionPerformed
        if(txtMaSach.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Chọn sách cần gia hạn! \n");
        }
        else{
            String sl = TraSachDAO.Instance().getSLGiaHan(txtMaDG.getText(), txtMaSach.getText());
            try {
                if(sl.equals("3")){
                    JOptionPane.showMessageDialog(rootPane, "Bạn chỉ được gia hạn tối đa 3 lần!");
                }
                else{
                    TraSachDAO.Instance().giaHan(txtMaDG.getText(), txtMaSach.getText());
                    btQuetDGActionPerformed(evt);
                    JOptionPane.showMessageDialog(rootPane, "Gia hạn thành công!");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Lỗi!\n Kiểm tra lại maCS.");
            }
        }
    }//GEN-LAST:event_btGiaHanActionPerformed

    private void btThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btThoatActionPerformed

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        jfMainMenu home = new jfMainMenu(Acc);
                
        home.setVisible(true);
        home.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btBackActionPerformed

    private void btMatSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMatSachActionPerformed
       
         if(txtMaSach.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Chọn sách cần báo mất! \n");
        }
         else{
             try {
            TraSachDAO.Instance().baoMatSach(txtMaDG.getText(), txtMaSach.getText());
            lbTichDiem.setText("-20đ");
            lbTichDiem.setForeground(new java.awt.Color(255, 51, 51));
            JOptionPane.showMessageDialog(rootPane, "Báo mất thành công!");
            btQuetDGActionPerformed(evt);
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Lỗi! \n Kiểm tra lại maDG, maCS.");
        }
         }
        
    }//GEN-LAST:event_btMatSachActionPerformed

    private void btQuetDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuetDGActionPerformed
        
        List<String> listDG = MuonSachDAO.Instance().getListMaDG();
        if(!listDG.contains(txtMaDG.getText().toUpperCase())){
            JOptionPane.showMessageDialog(rootPane, "MaDG không tồn tại! \n");
        }
        else{
            DefaultTableModel tabModel = (DefaultTableModel) tableThongTinSachMuon.getModel();
            tabModel.setRowCount(0);
            List<TraSachDTO> list = TraSachDAO.Instance().getTableTraSach(txtMaDG.getText());
            
            if(list.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Đọc giả này đã trả hết sách!\n!");
            }
            
             list.forEach((item) -> {
                tabModel.addRow(new Object[]{
                    item.getMaPM(), item.getMaCS(), item.getTenCS(), item.getNgayMuon(), item.getNgayHetHan(), item.getTrangThai()
                });
            });
        }
    }//GEN-LAST:event_btQuetDGActionPerformed

    private void tableThongTinSachMuonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableThongTinSachMuonMouseClicked
        
        if(evt.getClickCount() == 2){
        int index = tableThongTinSachMuon.getSelectedRow();
        TableModel model = tableThongTinSachMuon.getModel();
 
        txtMaSach.setText(model.getValueAt(index, 1).toString());
        
        }
        
    }//GEN-LAST:event_tableThongTinSachMuonMouseClicked

    private void btQuetDGMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btQuetDGMouseMoved
        setColor(btQuetDG);
    }//GEN-LAST:event_btQuetDGMouseMoved

    private void btTraSachMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btTraSachMouseMoved
        setColor(btTraSach);
    }//GEN-LAST:event_btTraSachMouseMoved

    private void btGiaHanMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btGiaHanMouseMoved
        setColor(btGiaHan);// TODO add your handling code here:
    }//GEN-LAST:event_btGiaHanMouseMoved

    private void btMatSachMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMatSachMouseMoved
        setColor(btMatSach);// TODO add your handling code here:
    }//GEN-LAST:event_btMatSachMouseMoved

    private void btBackMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBackMouseMoved
        btBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/back_2.png")));
    }//GEN-LAST:event_btBackMouseMoved

    private void btThoatMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btThoatMouseMoved
        btThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Thoat_2.png")));
    }//GEN-LAST:event_btThoatMouseMoved

    private void pnTacVuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnTacVuMouseMoved
        resetColor(btQuetDG);
        resetColor(btTraSach);
        resetColor(btGiaHan);
        resetColor(btMatSach);
    }//GEN-LAST:event_pnTacVuMouseMoved

    private void pnTraSachMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnTraSachMouseMoved
        btBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/back.png")));
        btThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Thoat.png")));
    }//GEN-LAST:event_pnTraSachMouseMoved

    private void txtMaSachMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMaSachMouseMoved
        lbTichDiem.setText("");
    }//GEN-LAST:event_txtMaSachMouseMoved

    private void pnDSMuonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnDSMuonMouseMoved
        lbTichDiem.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_pnDSMuonMouseMoved

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfTraSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfTraSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfTraSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfTraSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfTraSach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btGiaHan;
    private javax.swing.JButton btMatSach;
    private javax.swing.JButton btQuetDG;
    private javax.swing.JButton btThoat;
    private javax.swing.JButton btTraSach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTichDiem;
    private javax.swing.JPanel pnDSMuon;
    private javax.swing.JPanel pnTacVu;
    private javax.swing.JPanel pnTraSach;
    private javax.swing.JTable tableThongTinSachMuon;
    private javax.swing.JTextField txtMaDG;
    private javax.swing.JTextField txtMaSach;
    // End of variables declaration//GEN-END:variables
}
